apiVersion: v1
kind: Pod
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  containers:
    - name: app
      image: k8s.gcr.io/guestbook:v3
      ports:
        - name: web
          containerPort: 3000
          protocol: TCP
